version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    volumes:
      - .:/app
    environment:
      CGO_ENABLED: 0
    depends_on:
      postgres: # Start after postgres only
        condition: service_healthy
    command: go run main.go

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck: # Tell Go the DB is up
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  postgres-db:
