version: '3.8'

services:
  web:
    profiles:
      - run
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      CGO_ENABLED: 0
    depends_on:
      db:
        condition: service_healthy
    command: go run main.go

  test:
    profiles:
      - test
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      CGO_ENABLED: 0
    depends_on:
      db:
        condition: service_healthy
    command: go test .

  db:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  postgres-db:
