version: '3.8'

services:

  test:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      CGO_ENABLED: 0
    depends_on:
      postgres:
        condition: service_healthy
    command: go test .


  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5
