/*
 * Customer segmentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: bouncepaw2@ya.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"avito2023/db"
	"log"
	"net/http"

	sw "avito2023/web"
)

func main() {
	defer db.Close()
	log.Println("Server started")
	log.Fatal(http.ListenAndServe(":8080", sw.NewRouter()))
}
