/*
 * Customer segmentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: bouncepaw2@ya.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateSegmentBody struct {
	// Name of a new segment. You cannot use a name that an existing segment or a segment that was deleted used.
	Name string `json:"name"`
	// Probabillity that new known users will also be part of this segment without explicitly requesting so. Default: 0.
	Percent int32 `json:"percent,omitempty"`
}
