/*
 * Customer segmentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: bouncepaw2@ya.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2002 struct {
	Status string `json:"status"`

	Error_ string `json:"error,omitempty"`
	// Link starts with /. Request the file at the same server.
	Link string `json:"link,omitempty"`
}
