/*
 * Customer segmentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: bouncepaw2@ya.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateUserBody struct {
	Id int32 `json:"id"`
	// Segments to add the user to. Duplicates are ignored.
	AddToSegments []string `json:"add_to_segments,omitempty"`
	// Segments to remove the user from. Duplicates are ignored.
	RemoveFromSegments []string `json:"remove_from_segments,omitempty"`
	// Time to live. Seconds to wait before removing the user from all the `add_to_segments` segments.
	Ttl int32 `json:"ttl,omitempty"`
}
