/*
 * Customer segmentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: bouncepaw2@ya.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateUserBody struct {
	Name int32 `json:"name,omitempty"`

	AddToSegments []string `json:"add_to_segments,omitempty"`

	RemoveFromSegments []string `json:"remove_from_segments,omitempty"`
}
