name: Test
on:
  - push

jobs:
  tester:
    name: Tester
    runs-on: alpine-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose-testing.yml"
          down-flags: "--volumes"
